# Generated by Django 4.2.5 on 2023-10-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercourse',
            name='start_date',
            field=models.DateField(verbose_name='Дата старта потока'),
        ),
    ]
