# Generated by Django 4.2.4 on 2023-09-04 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customgroup_customuser_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='group',
        ),
        migrations.DeleteModel(
            name='CustomGroup',
        ),
    ]
