# Generated by Django 4.2.5 on 2023-11-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_registercourse_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
