# Generated by Django 4.2 on 2025-09-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlessonprogress',
            name='course',
        ),
        migrations.RemoveField(
            model_name='userlessonprogress',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='userlessonprogress',
            name='module',
        ),
        migrations.RemoveField(
            model_name='userlessonprogress',
            name='user',
        ),
        migrations.DeleteModel(
            name='RegisterCourse',
        ),
        migrations.DeleteModel(
            name='UserLessonProgress',
        ),
    ]
