# Generated by Django 4.2.5 on 2023-09-11 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0007_alter_module_options_alter_lesson_description'),
        ('users', '0003_remove_customuser_group_delete_customgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='courses_learn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.course', verbose_name='Преподаю курсы'),
        ),
    ]
