# Generated by Django 4.2.5 on 2023-09-11 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0007_alter_module_options_alter_lesson_description'),
        ('users', '0004_customuser_courses_learn'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='courses_teach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.course', verbose_name='Преподаю курсы'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='courses_learn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_course', to='lesson.course', verbose_name='Прохожу курсы'),
        ),
    ]
