# Generated by Django 4.2.5 on 2024-02-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercourse',
            name='status',
            field=models.CharField(choices=[('wait', 'Ожидание'), ('rejected', 'Отколнена'), ('approved', 'Одобрена')], default='wait', max_length=9, verbose_name='Статус заявки'),
        ),
    ]
