# Generated by Django 4.2.5 on 2023-09-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0007_alter_module_options_alter_lesson_description'),
        ('users', '0005_customuser_courses_teach_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='courses_learn',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='courses_teach',
        ),
        migrations.AddField(
            model_name='customuser',
            name='courses_learn',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_course', to='lesson.course', verbose_name='Прохожу курсы'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='courses_teach',
            field=models.ManyToManyField(blank=True, null=True, to='lesson.course', verbose_name='Преподаю курсы'),
        ),
    ]
