# Generated by Django 4.2.5 on 2024-04-01 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_registercourse_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registercourse',
            name='start_date',
        ),
    ]
