# Generated by Django 4.2.5 on 2024-05-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_registercourse_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_tutor_student',
            field=models.BooleanField(default=False),
        ),
    ]
