# Generated by Django 4.2.5 on 2023-09-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0007_alter_module_options_alter_lesson_description'),
        ('users', '0007_customuser_is_student_customuser_is_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='courses_learn',
            field=models.ManyToManyField(blank=True, related_name='user_course', to='lesson.course', verbose_name='Прохожу курсы'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='courses_teach',
            field=models.ManyToManyField(blank=True, to='lesson.course', verbose_name='Преподаю курсы'),
        ),
    ]
