# Generated by Django 4.2.5 on 2024-05-01 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_module_description'),
        ('users', '0007_customuser_is_tutor_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='registercourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_start', models.DateTimeField(verbose_name='Дата и время начала')),
                ('hour_amount', models.IntegerField(default=1, verbose_name='Кол-во часов')),
                ('is_cancelled', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
        ),
    ]
