# Generated by Django 4.2.5 on 2024-05-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_registercourse_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание занятий', 'verbose_name_plural': 'Расписание занятий'},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='datetime_start',
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_start',
            field=models.TimeField(default=None, verbose_name='Время начала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='weekday',
            field=models.CharField(choices=[('1', 'Понедельник'), ('2', 'Вторник'), ('3', 'Среда'), ('4', 'Четверг'), ('5', 'Пятница'), ('6', 'Суббота'), ('7', 'Воскресенье')], default=True, max_length=19, verbose_name='Статус заявки'),
            preserve_default=False,
        ),
    ]
