# Generated by Django 4.2.5 on 2024-05-01 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_schedule_weekday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='is_cancelled',
        ),
        migrations.CreateModel(
            name='CancelledLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cancell', models.DateField(verbose_name='Дата отмены занятия')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='сancelled', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_cancelled',
            field=models.ManyToManyField(blank=True, related_name='schedule', to='users.cancelledlesson', verbose_name='Отменённые занятия'),
        ),
    ]
