# Generated by Django 4.2.5 on 2024-05-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_schedule_is_cancelled_cancelledlesson_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancelledlesson',
            options={'verbose_name': 'Отмена занятия', 'verbose_name_plural': 'Отмена занятий'},
        ),
        migrations.RenameField(
            model_name='cancelledlesson',
            old_name='date_cancell',
            new_name='date_cancelled',
        ),
    ]
