# Generated by Django 4.2.5 on 2025-04-21 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_cancelledlesson_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='background_image',
        ),
    ]
