version: '3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgre_base:/var/lib/postgresql/data/
    env_file:
      - .env

  web:
    build:
      context: ../pydep
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
volumes:
  static_value:
  media_value:
  postgre_base:
