CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "lesson_lesson" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(255) NOT NULL, "description" text NOT NULL);
CREATE TABLE IF NOT EXISTS "lesson_modulesincourse" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "sequence_number" integer NOT NULL, "course_id" bigint NOT NULL REFERENCES "lesson_course" ("id") DEFERRABLE INITIALLY DEFERRED, "module_id" bigint NOT NULL REFERENCES "lesson_module" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "lesson_lessonsinmodule" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "lesson_id" bigint NOT NULL REFERENCES "lesson_lesson" ("id") DEFERRABLE INITIALLY DEFERRED, "module_id" bigint NOT NULL REFERENCES "lesson_module" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "lesson_modulesincourse_course_id_f3eec8f2" ON "lesson_modulesincourse" ("course_id");
CREATE INDEX "lesson_modulesincourse_module_id_b1027246" ON "lesson_modulesincourse" ("module_id");
CREATE INDEX "lesson_lessonsinmodule_lesson_id_de19e19f" ON "lesson_lessonsinmodule" ("lesson_id");
CREATE INDEX "lesson_lessonsinmodule_module_id_adcb2923" ON "lesson_lessonsinmodule" ("module_id");
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "users_customuser_courses_learn" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "customuser_id" bigint NOT NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "course_id" bigint NOT NULL REFERENCES "lesson_course" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "users_customuser_courses_teach" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "customuser_id" bigint NOT NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "course_id" bigint NOT NULL REFERENCES "lesson_course" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "users_customuser_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "customuser_id" bigint NOT NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "users_customuser_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "customuser_id" bigint NOT NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "users_cancelledlesson" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "date_cancelled" date NOT NULL, "student_id" bigint NOT NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "users_schedule" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "weekday" varchar(19) NOT NULL, "time_start" time NOT NULL, "hour_amount" integer NOT NULL, "student_id" bigint NOT NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "users_schedule_is_cancelled" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "schedule_id" bigint NOT NULL REFERENCES "users_schedule" ("id") DEFERRABLE INITIALLY DEFERRED, "cancelledlesson_id" bigint NOT NULL REFERENCES "users_cancelledlesson" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "users_registercourse" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "status" varchar(9) NOT NULL, "course_id" bigint NOT NULL REFERENCES "lesson_course" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "users_customuser_courses_learn_customuser_id_course_id_7dded1ea_uniq" ON "users_customuser_courses_learn" ("customuser_id", "course_id");
CREATE INDEX "users_customuser_courses_learn_customuser_id_23e647e4" ON "users_customuser_courses_learn" ("customuser_id");
CREATE INDEX "users_customuser_courses_learn_course_id_9ccac445" ON "users_customuser_courses_learn" ("course_id");
CREATE UNIQUE INDEX "users_customuser_courses_teach_customuser_id_course_id_fd5e6ec8_uniq" ON "users_customuser_courses_teach" ("customuser_id", "course_id");
CREATE INDEX "users_customuser_courses_teach_customuser_id_94647236" ON "users_customuser_courses_teach" ("customuser_id");
CREATE INDEX "users_customuser_courses_teach_course_id_aee63733" ON "users_customuser_courses_teach" ("course_id");
CREATE UNIQUE INDEX "users_customuser_groups_customuser_id_group_id_76b619e3_uniq" ON "users_customuser_groups" ("customuser_id", "group_id");
CREATE INDEX "users_customuser_groups_customuser_id_958147bf" ON "users_customuser_groups" ("customuser_id");
CREATE INDEX "users_customuser_groups_group_id_01390b14" ON "users_customuser_groups" ("group_id");
CREATE UNIQUE INDEX "users_customuser_user_permissions_customuser_id_permission_id_7a7debf6_uniq" ON "users_customuser_user_permissions" ("customuser_id", "permission_id");
CREATE INDEX "users_customuser_user_permissions_customuser_id_5771478b" ON "users_customuser_user_permissions" ("customuser_id");
CREATE INDEX "users_customuser_user_permissions_permission_id_baaa2f74" ON "users_customuser_user_permissions" ("permission_id");
CREATE INDEX "users_cancelledlesson_student_id_defbd762" ON "users_cancelledlesson" ("student_id");
CREATE INDEX "users_schedule_student_id_0b15f88b" ON "users_schedule" ("student_id");
CREATE UNIQUE INDEX "users_schedule_is_cancelled_schedule_id_cancelledlesson_id_348b82f7_uniq" ON "users_schedule_is_cancelled" ("schedule_id", "cancelledlesson_id");
CREATE INDEX "users_schedule_is_cancelled_schedule_id_8f396e57" ON "users_schedule_is_cancelled" ("schedule_id");
CREATE INDEX "users_schedule_is_cancelled_cancelledlesson_id_ed7c308c" ON "users_schedule_is_cancelled" ("cancelledlesson_id");
CREATE UNIQUE INDEX "users_registercourse_user_id_course_id_485b1832_uniq" ON "users_registercourse" ("user_id", "course_id");
CREATE INDEX "users_registercourse_course_id_f71e71be" ON "users_registercourse" ("course_id");
CREATE INDEX "users_registercourse_user_id_8faad055" ON "users_registercourse" ("user_id");
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE TABLE IF NOT EXISTS "thumbnail_kvstore" ("key" varchar(200) NOT NULL PRIMARY KEY, "value" text NOT NULL);
CREATE TABLE IF NOT EXISTS "lesson_course" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(50) NOT NULL UNIQUE, "description" text NOT NULL, "price" integer NOT NULL, "image" varchar(100) NOT NULL, "programming_language" varchar(255) NOT NULL, "duration" integer NOT NULL, "category" varchar(50) NOT NULL, "level" varchar(50) NOT NULL, "category_id" bigint NULL REFERENCES "lesson_category" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "lesson_category_course" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "category_id" bigint NOT NULL REFERENCES "lesson_category" ("id") DEFERRABLE INITIALLY DEFERRED, "course_id" bigint NOT NULL REFERENCES "lesson_course" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "lesson_category_course_category_id_course_id_2fed194c_uniq" ON "lesson_category_course" ("category_id", "course_id");
CREATE INDEX "lesson_category_course_category_id_fbfe18eb" ON "lesson_category_course" ("category_id");
CREATE INDEX "lesson_category_course_course_id_785e861a" ON "lesson_category_course" ("course_id");
CREATE INDEX "lesson_course_category_id_00d82b6a" ON "lesson_course" ("category_id");
CREATE TABLE IF NOT EXISTS "lesson_category" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(50) NOT NULL UNIQUE, "slug" varchar(50) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "lesson_module" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(255) NOT NULL UNIQUE, "description" text NOT NULL, "image" varchar(100) NOT NULL);
CREATE TABLE IF NOT EXISTS "users_customuser" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "username" varchar(50) NOT NULL UNIQUE, "email" varchar(50) NOT NULL UNIQUE, "image" varchar(100) NULL, "description" text NOT NULL, "first_name" varchar(50) NOT NULL, "last_name" varchar(50) NOT NULL, "birthday" datetime NOT NULL, "is_teacher" bool NOT NULL, "is_tutor_student" bool NOT NULL, "is_tutor_admin" bool NOT NULL, "payment" integer NULL, "is_student" bool NOT NULL);
CREATE TABLE IF NOT EXISTS "lesson_userlessonprogress" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "completed" bool NOT NULL, "lesson_id" bigint NOT NULL REFERENCES "lesson_lesson" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "current" bool NOT NULL, "course_id" bigint NOT NULL REFERENCES "lesson_course" ("id") DEFERRABLE INITIALLY DEFERRED, "module_id" bigint NOT NULL REFERENCES "lesson_module" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "lesson_userlessonprogress_lesson_id_6f455e3a" ON "lesson_userlessonprogress" ("lesson_id");
CREATE INDEX "lesson_userlessonprogress_user_id_ee003b91" ON "lesson_userlessonprogress" ("user_id");
CREATE INDEX "lesson_userlessonprogress_course_id_2902ddca" ON "lesson_userlessonprogress" ("course_id");
CREATE INDEX "lesson_userlessonprogress_module_id_825c28c1" ON "lesson_userlessonprogress" ("module_id");
CREATE TABLE IF NOT EXISTS "lesson_projectdocument" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL, "description" text NULL, "file" varchar(100) NOT NULL);
