# Generated by Django 4.2.5 on 2023-10-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=True, upload_to='courses', verbose_name='Логотип курса'),
            preserve_default=False,
        ),
    ]
