# Generated by Django 4.2 on 2025-09-11 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_userlessonprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectDocument',
        ),
        migrations.RemoveField(
            model_name='modulesincourse',
            name='sequence_number',
        ),
    ]
