# Generated by Django 4.2.4 on 2023-08-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_remove_module_lessons_lessonsinmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='lessons',
            field=models.ManyToManyField(to='lesson.lesson'),
        ),
        migrations.DeleteModel(
            name='LessonsInModule',
        ),
    ]
