# Generated by Django 4.2 on 2025-11-13 21:23

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_lesson_content_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
