# Generated by Django 4.2.4 on 2023-08-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_alter_group_options_alter_lessonincourse_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
