# Generated by Django 4.2.5 on 2023-11-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(default=True, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
