# Generated by Django 4.2.4 on 2023-09-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_module_lessons_delete_lessonsinmodule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomGroup',
        ),
    ]
