# Generated by Django 4.2.5 on 2025-04-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='image',
            field=models.ImageField(null=True, upload_to='courses/modules', verbose_name='Логотип модуля'),
        ),
    ]
