# Generated by Django 4.2 on 2025-11-14 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson', '0004_course_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='authors',
            field=models.ManyToManyField(related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Авторы'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='authors',
            field=models.ManyToManyField(related_name='lessons', to=settings.AUTH_USER_MODEL, verbose_name='Авторы'),
        ),
        migrations.AddField(
            model_name='module',
            name='authors',
            field=models.ManyToManyField(related_name='modules', to=settings.AUTH_USER_MODEL, verbose_name='Авторы'),
        ),
    ]
