# Generated by Django 4.2.5 on 2025-04-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_module_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='image',
            field=models.ImageField(default=True, upload_to='courses/modules', verbose_name='Логотип модуля'),
            preserve_default=False,
        ),
    ]
