# Generated by Django 4.2.4 on 2023-09-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_customgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='customgroup',
            name='learn_courses',
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='modules',
            field=models.ManyToManyField(through='lesson.ModulesInCourse', to='lesson.module', verbose_name='Модули'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=1000, verbose_name='Цена'),
        ),
    ]
