# Generated by Django 4.2 on 2025-11-15 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson', '0005_course_authors_lesson_authors_module_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsinmodule',
            name='sequence_number',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер урока'),
        ),
        migrations.AddField(
            model_name='modulesincourse',
            name='sequence_number',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер модуля'),
        ),
        migrations.AlterField(
            model_name='course',
            name='authors',
            field=models.ManyToManyField(related_name='authored_courses', to=settings.AUTH_USER_MODEL, verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='authors',
            field=models.ManyToManyField(related_name='authored_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='module',
            name='authors',
            field=models.ManyToManyField(related_name='authored_modules', to=settings.AUTH_USER_MODEL, verbose_name='Авторы'),
        ),
    ]
