# Generated by Django 4.2.5 on 2025-04-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_userlessonprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlessonprogress',
            options={'verbose_name': 'Прогресс прохождения урока', 'verbose_name_plural': 'Прогресс прохождения уроков'},
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
