# Generated by Django 4.2.5 on 2025-05-28 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0007_alter_userlessonprogress_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonsinmodule',
            name='sequence_number',
        ),
    ]
