# Generated by Django 4.2.5 on 2023-09-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0007_alter_module_options_alter_lesson_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='programming_language',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
