# Generated by Django 4.2.5 on 2023-09-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0008_course_programming_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomGroup',
        ),
    ]
