# Generated by Django 4.2.5 on 2025-06-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0008_remove_lessonsinmodule_sequence_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Техническое задание',
                'verbose_name_plural': 'Технические задания',
            },
        ),
    ]
