# Generated by Django 4.2.5 on 2025-06-29 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0009_projectdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlessonprogress',
            name='course',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='module',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.module'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='file',
            field=models.FileField(upload_to='projects/'),
        ),
    ]
